name: wind_data
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy>=1.23
  - pandas>=1.5
  - scipy>=1.8
  - matplotlib>=3.7
  - pyqt=5                     
  - requests>=2.28
  - plotly>=5.10
  - python-docx>=0.8
  - geopy>=2.2
  # - meteostat
  - cdsapi>=0.5
  - pydeck>=0.8
  - papermill>=2.4
  - pip
  - pip:
      - windrose>=1.8.0
      - meteostat>=1.7.6
      - seaborn
      
